### PR TITLE
Add initial docker setup

### PR DESCRIPTION
**Pull request by jonasrosland**
This creates a Dockerfile and docker-compose.yml, to quickly get this plugin up and running.
The volume for YouTube media needs to be in the location mentioned in config.json.

### CODE REVIEW

**Comment by bbilly1** [comment]
Nice, thanks for getting the ball rolling on this one! 

I think for a docker container we should implement the configuration over environment variables instead. It's quite uncommon to pass a config.json into a container, that was just a quick and dirty way to implement this little script. You see there is already a [`get_config`](https://github.com/tubearchivist/jellyfin/blob/master/src/config.py#L8) function, that at the moment just reads the json file. How about if the file does not exist, try to get the config values from the environment? Then as long as you return the same ConfigType, the rest should work identical, docker and regular. 

Then for building the image, you can copy the files directly from the folder structure. That will go somewhere in a CI/CD, so we will have the full repo available for building the container. So you don't need git in the container and depend on github to build the image and we can build and push it from anywhere.

**Comment by jonasrosland** [comment]
I'm all for that! Didn't want to change any code in case the config file was still the way to go. Glad to hear it's not. I'm not a pro at Python, but I can give it a try if you'd like?

**Comment by bbilly1** [comment]
please give it a go, you'll be a pro in no time! :-) 

I'd suggest to hard code the video path in the container to /youtube. because that will be the volume, also in the example compose file, so that doesn't need to be configurable.

then I was thinking to install cron into the container or something like that, so this can be run automatically on an interval. but this can also be in a separate step.

**Comment by bbilly1** [comment]
excellent, that's some good progress, thanks for your contribution!

**Pull request merged**
